apiVersion: apps/v1
kind: Deployment
metadata:
  name: server2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server2
  template:
    metadata:
      labels:
        app: server2
    spec:
      containers:
      - name: server2-container
        image: jsninad/server2-image:latest
        ports:
        - containerPort: 5001

